#! /bin/sh

bspc monitor -d 1 2 3

bspc config normal_border_color  "#000000"
bspc config focused_border_color "#000000"
bspc config border_width         1
bspc config window_gap           -1
bspc config top_padding          0
bspc config split_ratio          0.39
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config presel_feedback_color "#CCCCCC"

# bspc rule -a TelegramDesktop desktop='^2' follow=on
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

