windows:
- geometry: !!binary |
    AdnQywADAAD//////////wAAAm8AAAOEAAAAAAAAAAAAAAJuAAADgwAAAAAAAAAABkAAAAAAAAAA
    AAAAAm4AAAOD
  tabs:
  - history:
    - active: true
      last_visited: '2023-10-06T23:24:06'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: DuckDuckGo — Privacy, simplified.
      url: https://start.duckduckgo.com/
      zoom: 0.9
  - active: true
    history:
    - active: true
      last_visited: '2023-10-06T23:24:06'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: qutebrowser quickstart | qutebrowser
      url: https://www.qutebrowser.org/quickstart.html
      zoom: 0.9
